development:
  adapter: postgresql
  encoding: utf8
  database: ibdb_dev
  pool: 5
  username: abraheem
  password: password
  port: 5432

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ibdb_test
  pool: 5
  username: abraheem
  password: password
  port: 5432


development:
  adapter: postgresql
  encoding: utf8
  database: ibdb_production
  pool: 5
  username: abraheem
  password: password
  port: 5432
  